# Generated by Django 5.1.2 on 2025-11-13 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField()),
                ('chunk_size', models.BigIntegerField()),
                ('total_chunks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_data', models.JSONField(help_text='List of chunk metadata including account, drive_file_id, checksum and size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_manifests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DriveFileManifest',
        ),
    ]
